Ready scripts for CI/CD builds and release jobs (#9)
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

diff --git a/etc/jenkins/Jenkinsfile_release b/etc/jenkins/Jenkinsfile_release
--- a/etc/jenkins/Jenkinsfile_release
+++ b/etc/jenkins/Jenkinsfile_release
@@ -2,9 +2,10 @@ node {
 
     def   MVN_HOME='/opt/tools/apache-maven/latest'
     def   HELP_PLUGIN='org.apache.maven.plugins:maven-help-plugin:2.1.1'
-    def   TARGET = 'deploy:deploy'
-    def   RELEASE_VERSION=''
-    def   NEXT_VERSION=''
+    def   CONFIG_FILE='~/etc/jenkins/Jenkinsfile_release_config'
+    def   TARGET = 'deploy'
+    def   RELEASE_VERSION=RELEASE_VERSION
+    def   NEXT_VERSION=NEXT_VERSION
     def   RELEASE_TAG=''
     def   OVERWRITE='false'
     def   PROJECT_NAME='JSTL-API'
@@ -13,7 +14,7 @@ node {
     def   REPO='git@github.com:eclipse-ee4j/jstl-api.git'
     def   CREDENTIALS_ID='github-bot-ssh'
     def   GIT_ORIGIN='origin'
-    def   RELEASE_FOLDER='api'
+    def   RELEASE_FOLDER=RELEASE_OPTION
     def   RELEASE_BRANCH=BRANCH
 
     env.JAVA_HOME="/opt/tools/java/oracle/jdk-8/1.8.0_181"
@@ -35,16 +36,21 @@ node {
             //# Compute release versions
             def SNAPSHOT_VERSION = sh(returnStdout: true, script: "${MVN_HOME}/bin/mvn -B ${HELP_PLUGIN}:evaluate -Dexpression=project.version 2> /dev/null | grep -E '^[0-9]+(.[0-9]+)+-SNAPSHOT\$'").trim()
 
-            if (!SNAPSHOT_VERSION?.trim()) {
-                error('-[ Missing required snapshot version number! ]----------------------------------')
-            } else {
-                def versionTokens = SNAPSHOT_VERSION.split('-')
-                RELEASE_VERSION = versionTokens[0]
+            if (!RELEASE_VERSION?.trim()) {
+                if (!SNAPSHOT_VERSION?.trim()) {
+                    error('-[ Missing required snapshot version number! ]----------------------------------')
+                } else {
+                    def versionTokens = SNAPSHOT_VERSION.split('-')
+                    RELEASE_VERSION = versionTokens[0]
+                }
             }
 
-            def (MAJOR_VERSION, MINOR_VERSION) = RELEASE_VERSION.tokenize('.')
-            def NEXT_MINOR_VERSION = (MINOR_VERSION as Integer) + 1
-            NEXT_VERSION = MAJOR_VERSION + '.' + NEXT_MINOR_VERSION + '-SNAPSHOT'
+            if (!NEXT_VERSION?.trim()) {
+                def (MAJOR_VERSION, MINOR_VERSION) = RELEASE_VERSION.tokenize('.')
+                def NEXT_MINOR_VERSION = (MINOR_VERSION as Integer) + 1
+                NEXT_VERSION = MAJOR_VERSION + '.' + NEXT_MINOR_VERSION + '-SNAPSHOT'
+            }
+
             RELEASE_TAG = RELEASE_VERSION + '-RELEASE'
 
             echo "Current version: ${SNAPSHOT_VERSION}"
@@ -58,24 +64,21 @@ node {
 
             if (DRY_RUN == 'true') {
                 echo '-[ Dry run turned on ]----------------------------------------------------------'
-                TARGET = 'install:install'
+                TARGET = 'install'
             }
         }
 
     }
     stage ('Prepare GPG') {
         withCredentials([file(credentialsId: '6a0be846-7284-4044-82de-6f4b02863628', variable: 'KEYRING')]) {
-            configFileProvider([configFile(fileId: '4dc08734-ea7f-4e97-8877-c76332d62377', targetLocation: '/home/jenkins/.m2/')]) {
-
-                //# Workaround: GPG initialization
-                sh("gpg --batch --import ${KEYRING}")
-                sh '''
+            //# Workaround: GPG initialization
+            sh("gpg --batch --import ${KEYRING}")
+            sh '''
                 for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u);
                 do
-                    echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust;
+                    echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust;
                 done
                 '''
-            }
         }
     }
     stage ('Prepare branch') {
@@ -121,14 +124,27 @@ node {
         echo '-[ Set Release version ]-------------------------------------------------------'
         sh """
         cd ${RELEASE_FOLDER}
-        ${MVN_HOME}/bin/mvn -q versions:set -DremoveSnapshot
+        ${MVN_HOME}/bin/mvn -q versions:set -DnewVersion=${RELEASE_VERSION}
         ${MVN_HOME}/bin/mvn -q versions:commit
         """
         echo '-[ Run release build ]---------------------------------------------------------'
         dir (RELEASE_FOLDER) {
-            configFileProvider([configFile(fileId: 'bb2b60c3-3444-4a60-9253-769fbffab593', variable: 'MAVEN_SETTINGS_XML')]) {
-                sh "${MVN_HOME}/bin/mvn -q -s ${MAVEN_SETTINGS_XML} -DskipTests -Ddoclint=none -Dadditionalparam='-Xdoclint:none' " +
-                        " -U -C clean package source:jar javadoc:jar gpg:sign ${TARGET}"
+            withCredentials([file(credentialsId: '6a0be846-7284-4044-82de-6f4b02863628', variable: 'KEYRING')]) {
+                configFileProvider([configFile(fileId: '4dc08734-ea7f-4e97-8877-c76332d62377', targetLocation: '/home/jenkins/.m2/')]) {
+
+                    //# Workaround: GPG initialization
+                    sh("gpg --batch --import ${KEYRING}")
+                    sh '''
+                        for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u);
+                        do
+                            echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust;
+                        done
+                       '''
+                    configFileProvider([configFile(fileId: 'bb2b60c3-3444-4a60-9253-769fbffab593', variable: 'MAVEN_SETTINGS_XML')]) {
+                        sh "${MVN_HOME}/bin/mvn -q -B -s ${MAVEN_SETTINGS_XML} -DskipTests -Ddoclint=none -Dadditionalparam='-Xdoclint:none' " +
+                                " -U -C clean package source:jar javadoc:jar ${TARGET}"
+                    }
+                }
             }
         }
     }
@@ -141,7 +157,7 @@ node {
         sh "git tag -m ${RELEASE_TAG} -a ${RELEASE_TAG}"
         echo '-[ Set next snapshot version ]-------------------------------------------------'
         dir (RELEASE_FOLDER) {
-            sh "${MVN_HOME}/bin/mvn -q versions:set -DnextSnapshot"
+            sh "${MVN_HOME}/bin/mvn -q versions:set -DnewVersion=${NEXT_VERSION}"
             sh "${MVN_HOME}/bin/mvn -q versions:commit"
         }
         echo '-[ Perform commit to git ]-----------------------------------------------------'
